
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-deployment
  labels:
    app: py-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-pod
  
  template:
    metadata:
      name: py-pod
      labels:
        app: py-pod
spec:
    containers:
      - name: backend
        image: 803772965863.dkr.ecr.ap-southeast-1.amazonaws.com/backend
        imagePullPolicy: Never
        ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
   name: py-service
   labels:
     app: py-service
      
spec:
   type: LoadBalancer
   ports:
     - protocol: TCP
       port: 8000
       targetPort: 8000
   selector:
     app: py-pod
